data = {
    "cards":[
        {"id":0, "text":"If you are studying/studied communcation drink 4 times." },
        {"id":1, "text":"$p0 tell the first name and age of each player. Every person whose name or age is screwed up can give out 2 drinks." },
        {"id":2, "text":"Those who don't fart infront of their partner, drink twice." },
        {"id":3, "text":"$p0 make up your mind: which player is the last one to get to sleep after a night out: $p1 or $p2? Nightowl takes 2 drinks." },
        {"id":4, "text":"$p0 drink 2 times if you have ever been rude to a teacher. Otherwise give out 2 drinks." },
        {"id":5, "text":"Would you rather be able to dance like Michael Jackson or sing like Freddie Mercury? Everyone vote at the same time, losers drink 4 times." },
        {"id":6, "text":"$p0 give $p1 free access to your instagram for 1 minute or finish your drink." },
        {"id":7, "text":"$p0 do an action ordered by $p1. If you refuse or can't do it drink 3 times." },
        {"id":8, "text":"Drink 4 sips if you've ever looked online for tips and tricks to lose weight without having to actually diet or workout." },
        {"id":9, "text":"$p0 drink as many sips as number of sex partners you've had." },
        {"id":10, "text":"$p0 drink as many sips as there are empty glasses or cans on the table." },
        {"id":11, "text":"$p0 sing the chorus from a Justin Bieber song or drink 3 times." },
        {"id":12, "text":"Drink 5 times if you've ever had sex in your parent's bed." },
        {"id":13, "text":"$p0 you can give out as many sips as you have uncles." },
        {"id":14, "text":"$p0 make up your mind: who would win in a push-up contest, $p1 or $p2? Mr.Biceps can give out 2 drinks." },
        {"id":15, "text":"The first player between $p0 and $p1 to touch the fridge hands out 2 drinks." },
        {"id":16, "text":"$p0 must choose the next song, those who like it drink 2 times." },
        {"id":17, "text":"$p0 give out as many sips as there are red clothes you are wearing. Drink 5 times if you don't have any on." },
        {"id":18, "text":"$p0 do a handstand or drink 3 times." },
        {"id":19, "text":"$p0 make up your mind: who do you think is more of a computer whiz, $p1 or $p2? Mark Zuckerberg must drink twice." },
        {"id":20, "text":"$p0, $p1, $p2 down your drinks." },
        {"id":21, "text":"Anyone who has lived in more that 3 towns drink twice." },
        {"id":22, "text":"Drink 2 times if you've already thought about having cosmetic surgery." },
        {"id":23, "text":"People with shoes over 60 dollars, drink 3 times." },
        {"id":24, "text":"$p0 if you are wearing flip flops give out 6 drinks, if not drink twice." },
        {"id":25, "text":"Twix or Snickers? Vote at the same time and losing side drinks 3 times." },


      /*  {"id":0, "text":"Drink if you've never watched Game of Thrones." },
        {"id":1, "text":"Everyone take a sip of your drink without using your hands." },
        {"id":2, "text":"Drink if you have mulitple alarms set on your phone that are only minutes apart." },
        {"id":3, "text":"Everyone guess my phone's battery percentage. The person who is closest picks someone else to drink." },
        {"id":4, "text":"If you have more than 3 keys on your key ring, drink up" },
        {"id":5, "text":"Which player can do the best impression of me? That person gives out a drink." },
        {"id":6, "text":"Drink if your Instagram bio includes the city or state you line in. By the way, nobody cares." },
        {"id":7, "text":"Take a drink if you own an Ivy League sweatshirt" },
        {"id":8, "text":"Do your best celebrity impression. The first person to correctly guess you identity chooses someone else to drink." },
        {"id":9, "text":"If a player is playing music right now, finish your drink you disrupting fuck." },
        {"id":10, "text":"If you linke cottage cheese take a drink, weirdo." },
        {"id":11, "text":"Drink if you've ever secretly thrown up at a party then acted like nothing happened." },
        {"id":12, "text":"All players who wished you a happy birthday this past year take a drink." },
        {"id":13, "text":"The player who organized this game gives out three drinks." },
        {"id":14, "text":"All players who have been on a date with another player must take a drink." },
        {"id":15, "text":"The two players who have known each other the longest take a drink together." },
        {"id":16, "text":"Take a drink if you've ever seen 'The Human Centipede'. Also explain yourself." },
        {"id":17, "text":"The player with the oldest phone must drink." },
        {"id":18, "text":"Every player who knows how to solve a Rubik's cube give out two drinks." },
        {"id":19, "text":"Take a drink if you've ever been to Coachella. Then shut up about it for the rest of the night." },
        {"id":20, "text":"Take a drink if you've seen every Harry Potter movie. No Muggles allowed this round." },
        {"id":21, "text":"Put on Eminem's 'Lose Yourself' and sing along. First person to laugh or forget a lyric takes a drink. Continue till everyone has drank or the song ends."},
        {"id":22, "text":"Everyone who is younger than you takes a drink"},
        {"id":23, "text":"Every player takes a drink for each year they had braces."},
        {"id":24, "text":"Take a drink if you own a pair of Vans but don't skate. Cheers, posers."},
        {"id":25, "text":"The player reading this card must drink. Keep it simple stupid."},
        {"id":26, "text":"Everyone who knows how to roll a joint takes a drink."},
        {"id":27, "text":"The organizer of the game nominates a player to give a heartfelt speech about what friendship means to them. Then they both take a drink."},
        {"id":28, "text":"Give out a drink for each ex-boyfriend/girlfriend you have."},
        {"id":29, "text":"Take a drink if you've ever given or received road head. Don't lie, you kinky bastards."},
        {"id":30, "text":"Take a drink if you currently have condom in your purse or wallet."},
        {"id":31, "text":"All players must reveal their first screen name. The person with the most embarrassing one must drink."},
        {"id":32, "text":"Drink if you've ever investing Bitcoin (if you can afford a sip)"},
        {"id":33, "text":"Drink if you ever studied abroad and 'it tooootally changed your life'."},
        {"id":34, "text":"Drink if you were in a fraternity or sorority"},
        {"id":35, "text":"Drink if you've ever been fired."},
        {"id":36, "text":"Drink if you played a varsity sport in high school."},
        {"id":37, "text":"Drink if you only can speak English."},
        {"id":38, "text":"Drink if you've ever been arrested."},
        {"id":39, "text":"Drink if you still have to go into work throughout quarantine."},
        {"id":40, "text":"Drink if you're on your period."},
        {"id":41, "text":"Drink if you've ever run from the police or campus security."},
        {"id":42, "text":"Drink if you actually purchased a fidget spinner in 2017."},
        {"id":43, "text":"Drink if you've participated in a Thanksgiving 5K"},
        {"id":44, "text":"Drink if you had a swimming pool growing up, you lucky bastard."},
        {"id":45, "text":"Drink if you took an AP class in high school, nerd."},
        {"id":46, "text":"Drink if you have a younger sibling. Congrats and paving the way for them."},
        {"id":47, "text":"Drink if you own a water bottle that has become like a child to you."},
        {"id":48, "text":"Drink if your family has a Costco Membership."},
        {"id":49, "text":"Drink if you ever took piano lessons as a kid."},
        {"id":50, "text":"Drink if you believe in ghosts."},
        {"id":51, "text":"Drink if you enjoy the smell of gasoline."},
        {"id":52, "text":"If you've been on a road trip longer than five hours, drink like you don't have to stop for a bathroom break."},
        {"id":53, "text":"Which player has the fullest drink right now? Take three drinks. Time to catch up buddy."},
        {"id":54, "text":"Players wearing all black: this isn't a funeral. Drink up."},
        {"id":55, "text":"Who has had the more regrettable hairstyle? That person gives a drink to the player of their choice."},
        {"id":56, "text":"Every player who's sitting cross-legged takes two drinks."},
        {"id":57, "text":"Every player who's a Scorpio takes a drink. Your parents probably fucked on Valentine's Day. Ever think about that?"},
        {"id":58, "text":"The player with the largest show size takes a drink. Also, congrats on the huge dick, bro."},
        {"id":59, "text":"Drink if you haven't eaten a vegetable today."},
        {"id":60, "text":"Drink if you've ever lost over $300 in a casino. Sorry for your loss."},
        {"id":61, "text":"On the count of 3, players say the name of the person they find the most likely to order chicken fingers at a fancy restaurant. Player with the most votes, drinks."},
        {"id":62, "text":"The player who has broken the most bones takes one drink for each break."},
        {"id":63, "text":"The youngest player takes a drink. Don't blame us; blame your parents for not fucking sooner."},
        {"id":64, "text":"If this is your first time playing this game, drink"},
        {"id":65, "text":"Reverse the rotation of the game. Everyone drinks."},
        {"id":66, "text":"The player reading this card gets to choose another player to finish their drink."},
        {"id":67, "text":"Drink if this is your third day drinking in a row."},
        {"id":68, "text":"All players take turns complimenting you. the player who gives the best compliment gives out a drink."},
        {"id":69, "text":"Everyone say their middle name. The player with the worst one drinks."},
        {"id":70, "text":"Choose a person to spell 'guarantee'. If they can't, send a drink their way."},
        {"id":71, "text":"Go around the circle saying the alphabet backwards. First person to fuck up drinks."},
        {"id":72, "text":"Vote on how to properly say 'Caramel'. Losing team drinks."},
        {"id":73, "text":"The tallest player and the shortest player take a drink together."},
        {"id":74, "text":"Which player is most likely to get high before a job interview? Person with the most votes drinks."},
        {"id":75, "text":"Anyone who has milked a cow, drink and tell us how it made you feel."},
        {"id":76, "text":"Mexican or Chinese food? Everyone votes, losing team drinks twice."},
        {"id":77, "text":"Which would you rather give up, oral sex or cheese? Everyone votes, losing team drinks."},
        {"id":78, "text":"Which player has the funniest losing their virginity story? Person with the most votes gets a pass; everyone else drinks."},
        {"id":79, "text":"Drink if you've ever been in Wyoming."},
        {"id":80, "text":"Everyone drinks once for every Apple product they own."},
        {"id":81, "text":"player reading this card must hum a song. First player to guess the song correctly gives out a drink."},
        {"id":82, "text":"Drink if you do your own taxes. But also congrats on being a real adult."},
        {"id":83, "text":"Drink if you have roommates. One drink for each one you have."},
        {"id":84, "text":"Vote which player is the horniest. Player with the most votes drinks. Try to cool down there champ."},
        {"id":85, "text":"Ketchup or mustard on a hot dog? losing team drinks. If you put both, also drink."},
        {"id":86, "text":"Which player can make the best horse noise? the player with the most votes gives out a drink."},
        {"id":87, "text":"Choose someone to play you in rock, paper scissors. Remaining players bet on who will win. Losers drink together in shame."},
        {"id":88, "text":"Any player with a cracked phone screen must drink."},
        {"id":89, "text":"Everyone who isn't following me on Instagram throw me a follow to help my ratio. Then drink."},
        {"id":90, "text":"Which player has the best smile? The person with the most votes drinks."},
        {"id":91, "text":"In a fight between the oldest and youngest players, who would win? The person with the most votes gives out two drinks."},
        {"id":92, "text":"If you're not following Beyonce on Instagram drink. How dare you?"},
        {"id":93, "text":"Drink if you've ever had mono."},
        {"id":94, "text":"Drink if youre in a serious relationship. One drink for each year you've been dating."},
        {"id":95, "text":"If you think pineapple belongs on pizza go fuck yourse- I mean drink."},
        {"id":96, "text":"Drink if you voted in the last election. Cheers to democracy."},
        {"id":97, "text":"Which player would be most likely to die first in a scary movie? player the most votes drinks."},
        {"id":98, "text":"If since quarantine started you spent an entire day in the same clothes, then went to bed in them too, drink up and get your life together."},
        {"id":99, "text":"Which player most needs to be checked into anger management? Player with the most votes drinks to CHILL THE FUCK OUT."},
        {"id":100, "text":"All players who have stickers on their laptops drink."},
        {"id":101, "text":"All players who have AirPods must drink. Also consider sending a $1 Venmo to all the other peasants in the room."},
        {"id":102, "text":"All players who have an Alexa or Google home drink."},
        {"id":103, "text":"All players check what color underwear they have on. Whoever is matching eachother, drink together."},       
        {"id":104, "text":"Next person to receive a text takes a drink."},       
        {"id":105, "text":"If you've ever owned Crocs, drink. Make better decisions in the future."},       
        {"id":106, "text":"If you currently volunteer somewherem take a break from saving the world and drink."},       
        {"id":107, "text":"If you've ever had a Tumblr, drink up."},       
        {"id":108, "text":"Anyone who has drunk texted an ex in the past month must drink."},       
        {"id":109, "text":"Everyone who has seen a dick on Chatroulette must drink."},       
        {"id":110, "text":"All players with an Uber rating of 4.5 or below must drink."},       
        {"id":111, "text":"Whoever is in the picture on their phone's background must drink."},       
        {"id":112, "text":"The player whose drink is the most full, take 2 sips. Try to keep up."},       
        {"id":113, "text":"Everyone votes on who looks the hottest in their ID pic. You can't vote for yourself. The winner picks someone else to drink."},       
        {"id":114, "text":"Whoever has a tattoo must drink then show everyone their dope ink."},       
        {"id":115, "text":"Players who are vegetarian, drink."},       
        {"id":116, "text":"The person who had coffee most recently have a drink."},       
        {"id":117, "text":"players who currently have chapstick with them, put those moisturized lips on your drink and take a smooth sip."},       
        {"id":118, "text":"Sleep talkers take a drink; sleep walkers take 2."},       
        {"id":119, "text":"If you took karate as a kid, show us your best karate chop, then take a drink."},       
        {"id":120, "text":"Those who have fooled around in a movie theater, drink twice. Then get a fucking room."},       
        {"id":121, "text":"If you've ever flown first class, put your pinky up and drink to being boujie."},       
        {"id":122, "text":"Everyone say what you were for Halloween last year. Everyone votes on the best costume, winner gives out a drink. If you didnt dress up, drink twice."},       
        {"id":123, "text":"If you had an inhaler growing up, inhale your beverage."},       
        {"id":124, "text":"If you do Yoga, you have plenty of headspace for another drink."},       
        {"id":125, "text":"Blondes, cheers to being the funnest."},       
        {"id":126, "text":"Drink if you've ever gone to class high."},       
        {"id":127, "text":"Quick: last person to slap their own ass drinks."},       
        {"id":128, "text":"Go around the circle and name different kinds of suchi rolls. First to fuck up drinks."},       
        {"id":129, "text":"Male players take a drink for each female player."},       
        {"id":130, "text":"Female players take a drink for each male player."},       
        {"id":131, "text":"take a drink if you don't know how old your mom is."},       
        {"id":132, "text":"take a drink if you're a pet owner. Cheers to your fur baby."},       
        {"id":133, "text":"Take a drinmk if your mom still makes your doctor appointments. And then grow the fuck up."},       
        {"id":134, "text":"Quick: everyone touch your head with both hands! Last person to do so drinks."},       
        {"id":135, "text":"Count to three, then everyone points at the player they want to take a drink. Drink as many times as you were pointed at."},       
        {"id":136, "text":"Everyone who has ever JUULed, drink."},       
        {"id":137, "text":"Whoever had to drink last round, drinks again, bitch."},       
        {"id":138, "text":"Everyone who has ever done Molly at a music festival takes a drink."},       
        {"id":139, "text":"The player that has smoked the most recently takes a drink (JUULs don't count. Get lung cancer like an adult)."},       
        {"id":140, "text":"Everyone who would rather be watching netflix right now drink."},    
        {"id":141, "text":"Drink if you're friends with your mom on Facebook xx"},    
        {"id":142, "text":"Everyone build up a drumroll until i decide who I'd like to drink."},    
        {"id":143, "text":"'Toy Story' or 'The Incredibles'? Everyone votes on which they prefer. Losing team drinks."},    
        {"id":144, "text":"Which player would be the leader of a prison gang? that person gives out a badass drink."},    
        {"id":145, "text":"on the count of 3, everyone say their favorite sex position. Whoever has the same answer, cheers and drink"},    
        {"id":146, "text":"Take turns naming fast food chains. First person to fuck up drinks."},    
        {"id":147, "text":"players who took band or orchestra in middle school must reveal their instrument and then take a drink."},    
        {"id":148, "text":"If you name is John, Jake, Michael, Sarah, Jessica, or Emma; drink on behalf of your parents' lack of originality."},    
        {"id":149, "text":"Every player with dyed hair takes a drink. you ain't foolin nobody."},    
        {"id":150, "text":"Every player with an outie belly button takes a drink, because that's odd as hell."},    
        {"id":151, "text":"Every player over six feet tall takes a drink for each inch over six feet."},    
        {"id":152, "text":"And the show must go on. If you were ever a theater kid, the spotlight is on you. Drink up!"},
        {"id":153, "text":"Players wearing a watch take a drink. We have cell phones for that now dummies."},
        {"id":154, "text":"Do you sleep on the right or left side of the bed? Everyone votes, losing team drinks. If you don't sleep on a specific side, drink twice."},
        {"id":155, "text":"All gingers take a drink. Sorry not sorry."},
        {"id":156, "text":"Every player who has dimples must drink up, you fuckin cuties."},
        {"id":157, "text":"Drink if you read the news today. You need that drink."},
        {"id":158, "text":"Which player would make the best motivational speaker. Vote and then that person drinks and gives us a little life wisdom."},
        {"id":159, "text":"All players with and Android phone must grip it n' sip it."},
        {"id":160, "text":"All players who are using someone else's Netflix account must drink. You can afford it."}*/
    ]
};